//314
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("4.2.314.0")]
[assembly: AssemblyFileVersion("4.2.314")]