//153
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("3.0.153.0")]
[assembly: AssemblyFileVersion("3.0.153")]